server:
  port: 9012
#  port: 9097
#  servlet:
#    session:
#      cookie:
#        name: mn

management:  #actuator
  server:
    port: 9098
  endpoints:
    web:
      #      base-path: / #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"  #打开全部请求端点
#        include: refresh,health,info #打开部分

mybatis-plus:
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true
    database-id: oracle
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  refresh-mapper: true

spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.120:1433;databasename=ecology
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Weaver#2012!@#

logging:
  level:
    com:
      insigma: DEBUG

